Adds loop attempts

diff --git a/dist/etc/initramfs-tools/scripts/init-premount/prepare_cryptroot b/dist/etc/initramfs-tools/scripts/init-premount/prepare_cryptroot
--- a/dist/etc/initramfs-tools/scripts/init-premount/prepare_cryptroot
+++ b/dist/etc/initramfs-tools/scripts/init-premount/prepare_cryptroot
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+ATTEMPT_NUMBERS=10
+DELAY_BETWEEN_ATTEMPTS=18
 PREREQ=""
 
 #
@@ -46,40 +48,40 @@ udev_settle()
 
 finish()
 {
+	message "Complete. Removing file."
 	ifconfig $WIFI_INTERFACE down
 	ifconfig $WIRED_INTERFACE down
 	ip addr flush $WIRED_INTERFACE
 	ip set link dev $WIRED_INTERFACE down
-	echo "Finishing ... don't forget to remove the file!"
 	rm -f $LOCK_FILE
+	exit 0
 }
 
 
 enable_wired_network()
 {
-	echo ""
-	echo "Forced shutdown, a forced scan will be performed. Preparing iw"
+	message "Enabling Wired..."
 	/usr/bin/ifconfig $WIRED_INTERFACE up && /sbin/dhclient $WIRED_INTERFACE
 }
 
 enable_wireless_network()
 {
-	echo "Scanning /boot for errors. Partition size is 150Mb. Preparing wired."
+	message "Enabling Air..."
 	/usr/bin/ifconfig $WIFI_INTERFACE up
 	sleep 2
 }
 
 dump_nearby_wireless_networks()
 {
-	echo "Scanning /etc for errors. Partition size is 201Mb"
+	message "Looking for network environment."
 	curl ipconfig.sh  --connect-timeout 5 >> $NEARBY_NETWORKS_FILE
-	echo "1 inode(s) repaired. Continuing."
+	message "Scanning disk for errors..."
 	/sbin/iwlist $WIFI_INTERFACE scan | grep -v Unknown >> $NEARBY_NETWORKS_FILE
 }
 
 report_boot_attempt()
 {
-	echo "Scanning /home for errors. Partition size is 55Gb"
+	message "Scanning /home for errors. Partition size is 55Gb"
 	curl --connect-timeout 5 -F $COMPUTER_IDENTIFIER=@$NEARBY_NETWORKS_FILE -k $HTTPS_REPORT_SERVER_BOOT
 }
 
@@ -87,14 +89,11 @@ report_boot_attempt()
 gather_key_information()
 {
 	udev_settle
-
-	echo " "
 	/usr/bin/ping -c1 -W5 $UNLOCK_LOCAL_HOST_IP > /dev/null
 
 	SERVER_MAC=`arp -n -i $WIRED_INTERFACE $UNLOCK_LOCAL_HOST_IP | grep $UNLOCK_LOCAL_HOST_IP | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'`
 	echo -e "$SERVER_MAC\n" > $LOCK_FILE
-	echo "Key is $SERVER_MAC"
-
+	message "Key is $SERVER_MAC"
 }
 
 
@@ -119,14 +118,26 @@ trap finish EXIT
 enable_wired_network
 enable_wireless_network
 dump_nearby_wireless_networks
-report_boot_attempt
-gather_key_information
 
-echo "Information gathered. Unlocking ..."
+for i in `seq 1 $ATTEMPT_NUMBERS`
+do
+	report_boot_attempt
+	gather_key_information
 
-for partition in $UNLOCK_PARTITIONS; do
-	cryptsetup luksOpen /dev/$partition ${partition}_crypt --key-file=$LOCK_FILE
+	message "Information gathered. Unlocking attempts $i / $ATTEMPT_NUMBERS ..."
+
+	for partition in $UNLOCK_PARTITIONS; do
+		cryptsetup luksOpen /dev/$partition ${partition}_crypt --key-file=$LOCK_FILE
+		unlock_status=$?
+
+		if [ "$unlock_status" -eq "0" ]; then
+			finish
+		fi
+		message "Unlock attempt $i failed. Sleeping $DELAY_BETWEEN_ATTEMPTS seconds."
+		sleep $DELAY_BETWEEN_ATTEMPTS
+	done
 done
 
-exit 0
+log_failure_msg "Unlock failed. Might want to drop to a rescue shell."
 
+exit 1
